# Generated by Django 2.0.4 on 2018-04-29 22:33

import Shop.models
import ckeditor.fields
import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breeder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Jmeno')),
                ('description', models.TextField(blank=True, verbose_name='Poznámka')),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Šlechtitel',
                'verbose_name_plural': 'Šlechtitelé',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=2018, verbose_name='Rok')),
                ('spring', models.BooleanField(default=False, verbose_name='Jaro')),
                ('rose_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Na skladě')),
                ('loose_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Dvojek')),
                ('grow', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ujmulo se')),
                ('implant', models.PositiveSmallIntegerField(null=True, verbose_name='Očkováno')),
            ],
            options={
                'verbose_name': 'Sklad',
                'verbose_name_plural': 'Sklady',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Barva')),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
            ],
            options={
                'verbose_name': 'Barva',
                'verbose_name_plural': 'Barvy',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Národnost')),
                ('shortcut', models.CharField(max_length=5, verbose_name='Zkratka státu')),
            ],
            options={
                'verbose_name': 'Národnost',
                'verbose_name_plural': 'Národnost',
            },
        ),
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Ocenění')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Popis')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveSmallIntegerField(default=120, verbose_name='Cenova skupina')),
            ],
            options={
                'verbose_name': 'Cena',
                'verbose_name_plural': 'Cenové skupiny',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True, verbose_name='Poznámka')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uživatel')),
            ],
            options={
                'verbose_name': 'profil',
                'verbose_name_plural': 'profily',
            },
        ),
        migrations.CreateModel(
            name='Rose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Název')),
                ('add_price', models.SmallIntegerField(default=0, verbose_name='Přidaná cena')),
                ('flower_size', models.PositiveSmallIntegerField(null=True, verbose_name='Velikost květu')),
                ('flower_kind', models.CharField(max_length=70, null=True, verbose_name='Typ květu')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Rok')),
                ('description', models.TextField(blank=True, verbose_name='Krátký popisek')),
                ('text', ckeditor.fields.RichTextField(blank=True, verbose_name='Popis růže')),
                ('added_date', models.DateField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(verbose_name='date published')),
                ('plants_per_m2', models.SmallIntegerField(blank=True, null=True, verbose_name='Na m2')),
                ('distance', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Rozestupy')),
                ('height', models.PositiveSmallIntegerField(null=True, verbose_name='Výška od')),
                ('max_height', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=' do')),
                ('width', models.PositiveSmallIntegerField(null=True, verbose_name='Šířka od')),
                ('max_width', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=' do')),
                ('growth_habit', models.CharField(blank=True, max_length=70, verbose_name='Tvar keře')),
                ('add_info', models.CharField(blank=True, max_length=300, verbose_name='Další informace')),
                ('fragrance', models.PositiveSmallIntegerField(choices=[(1, 'Málo'), (2, 'Trochu'), (3, 'Středně'), (4, 'Hodně')], null=True, verbose_name='Vůně')),
                ('hardiness', models.PositiveSmallIntegerField(choices=[(1, 'Málo'), (2, 'Trochu'), (3, 'Středně'), (4, 'Hodně')], null=True, verbose_name='Mrazuvzdornost')),
                ('black_spot', models.PositiveSmallIntegerField(choices=[(1, 'Málo'), (2, 'Trochu'), (3, 'Středně'), (4, 'Hodně')], null=True, verbose_name='Černá skvrnitost')),
                ('mildew', models.PositiveSmallIntegerField(choices=[(1, 'Málo'), (2, 'Trochu'), (3, 'Středně'), (4, 'Hodně')], default=3, verbose_name='Padlí')),
                ('breeder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shop.Breeder', verbose_name='Šlechtitel')),
                ('color', models.ManyToManyField(to='Shop.Color', verbose_name='Barva')),
                ('honor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shop.Honor', verbose_name='Ocenění')),
            ],
            options={
                'verbose_name': 'Růže',
                'verbose_name_plural': 'Růže',
                'ordering': ['-name', '-honor'],
            },
        ),
        migrations.CreateModel(
            name='RoseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, height_field='height_field', null=True, upload_to=Shop.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=230)),
                ('width_field', models.IntegerField(default=320)),
                ('of_rose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.Rose', verbose_name='Růže')),
            ],
            options={
                'verbose_name': 'obrázek',
                'verbose_name_plural': 'obrázky',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=21, verbose_name='Skupina')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Popis')),
            ],
            options={
                'verbose_name': 'Skupina',
                'verbose_name_plural': 'Skupiny růží',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=2018, verbose_name='Rok')),
                ('spring', models.BooleanField(default=False, verbose_name='Jaro')),
                ('rose_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Na skladě')),
                ('loose_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Dvojek')),
                ('grow', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ujmulo se')),
                ('implant', models.PositiveSmallIntegerField(null=True, verbose_name='Očkováno')),
                ('rose', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shop.Rose')),
            ],
            options={
                'verbose_name': 'Sklad',
                'verbose_name_plural': 'Sklady',
            },
        ),
        migrations.AddField(
            model_name='rose',
            name='img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shop.RoseImage', verbose_name='náhled růže'),
        ),
        migrations.AddField(
            model_name='rose',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shop.Price', verbose_name='Cena'),
        ),
        migrations.AddField(
            model_name='rose',
            name='section',
            field=models.ManyToManyField(to='Shop.Section', verbose_name='Skupina'),
        ),
        migrations.AddField(
            model_name='cart',
            name='rose',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shop.Rose'),
        ),
        migrations.AddField(
            model_name='breeder',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shop.Country'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('rose', 'year', 'spring')},
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('rose', 'year', 'spring')},
        ),
    ]
